#!/bin/bash

do_limit() {
	local argc=$#
	local mac="$1"
	local ip="$2"; shift 2
	local json="$*"

	if ((argc<2)); then
		return 1
	fi

	echo todo
	echo 1. move ip to ipset 'unauth'
	echo 2. set tc default
	echo 3. set nginx default
}

um_init() {
	echo todo
	echo 1. init global iptable
	echo 2. init global ipset
}

um_fini() {
	echo todo
	echo 1. clear global iptable
	echo 2. clear global ipset 
}

um_bind() {
	do_limit "$@"
}

um_unbind() {
	do_limit "$@"
}

um_auth() {
	do_limit "$@"
}

um_deauth() {
	local argc=$#
	local mac="$1"
	local ip="$2"
	local reason="$3"

	if ((3!=argc)); then
		return 1
	fi

	do_limit "${mac}" "${ip}"
	#
	# todo
	# 1. update website reason
	#
	echo "deauth $@"
}

main() {
	local action="$1"; shift

	case ${action} in
	init|fini|bind|unbind|auth|deauth)
		um_${action} "$@"
		;;
	*)
		return 1
		;;
	esac
}

main "$@"
