#!/bin/sh

echo "version $(cat /etc/.version)"

. /etc/env.in

mount -a

LDCONFIG=$(type -p ldconfig)
if [ -f "${LDCONFIG}" ]; then
    # Configuring dynamic linker
    echo "Configuring dynamic linker:"
    ${LDCONFIG} -C /tmp/ld.so.cache
else
    echo "Not find ldconfig"
fi

for initscript in /etc/init.d/S[0-9][0-9]*
do
    if [ -x $initscript ] ;
    then
        echo "[RCS]: $initscript"
        $initscript
    fi
done

#
# autelan init
#
# must NOT end with &
/etc/init.d/rc.autelan
