#!/bin/sh

echo "
    _____ __ __ _______ ______ __     _____ _ ___
   |  _  |  |  |       |   ___|  |   |  _  |  \  |
   | |_| |     |_     _|      |  |   | |_| |     |
   |  _  |     | |   | |   ___|  |___|  _  |     |
   |_| |_|_____| |___| |______|______|_| |_|__\__|

                     T H E  B E S T  W I R E L E S S
-----------------------------------------------------
"
echo "version $(cat /etc/.version)"

. /etc/env.in

# Mount fs accroding to /etc/fstab 
mount -a

LDCONFIG=$(type -p ldconfig)
if [ -f "${LDCONFIG}" ]; then
    # Configuring dynamic linker
    echo "Configuring dynamic linker:"
    ${LDCONFIG} -C /tmp/ld.so.cache
else
    echo "Not find ldconfig"
fi

for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done

#
# autelan init
#
#/etc/init.d/rc.autelan &
/etc/init.d/rc.autelan

