#!/bin/bash

acc_path=/tmp/config
acc_config=${acc_path}/acc.conf
acc_config_tmp=${acc_path}/.config_acc

#
# $1: delay, $2:interval, $3:command, $4:file, $5:file1, $6:interval1, $7:interval2
#
stop_function() {
	local delay="$1"
	local interval="$2"
	local command="$3"

	echo "${command}"
	command_kill ${command}
}

stop_main() {
	command_kill acc_init
}

main() {
	local tmp=${acc_config_tmp}

	sed '/#/d;/^$/d' ${acc_config} > ${tmp}

	local alias delay interval command file file1 interval1 interval2
	while read alias delay interval command file file1 interval1 interval2; do
		[[ "${alias}" = "acc_monitor" || "${alias}" = "move_log" || "${alias}" = "onoff_check" ]] \
			&& stop_function ${delay} ${interval} ${command}
	done < ${tmp}
	stop_main
}

main "$@"
