#!/bin/bash

func_path=/tmp/config
vcc_log=/tmp/vcc.log

#
# $1: command
#
start_onoff_check() {
	local command=$1
	local delay=0
	local interval=5
	local timeout=600
	local str_tmp=""
	
	str_tmp=$(get_confinfo acc.conf.onoff_check.delay)
	[[ ${str_tmp} != "null" ]] && delay=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.onoff_check.interval)
	[[ ${str_tmp} != "null" ]] && interval=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.onoff_check.timeout)
	[[ ${str_tmp} != "null" ]] && timeout=${str_tmp}

	sleep ${delay}
	${command} "${timeout}" "${interval}" &
}

#
# $1: command
#
start_move_log() {
	local command=$1
	local delay=0
	local interval=0
	local file=${vcc_log}
	local file1=vcc-quality-
	local str_tmp=""

	str_tmp=$(get_confinfo acc.conf.acc_monitor.vcc.file)
	[[ ${str_tmp} != "null" ]] && file=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.move_log.delay)
	[[ ${str_tmp} != "null" ]] && delay=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.move_log.file)
	[[ ${str_tmp} != "null" ]] && file1=${str_tmp}

	echo "${delay} ${interval} ${command} ${file} ${file1}"

	sleep ${delay}
	${command} ${file} ${file1}
}

#
# $1: command
#
start_acc_monitor() {
	local command=$1
	local delay=0
	local interval=1
	local file=${vcc_log}
	local file1=/tmp/.acc
	local interval1=900
	local interval2=10

	str_tmp=$(get_confinfo acc.conf.acc_monitor.delay)
	[[ ${str_tmp} != "null" ]] && delay=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.acc_monitor.interval)
	[[ ${str_tmp} != "null" ]] && interval=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.acc_monitor.timeout)
	[[ ${str_tmp} != "null" ]] && interval1=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.acc_monitor.path)
	[[ ${str_tmp} != "null" ]] && file1=${str_tmp}
	
	str_tmp=$(get_confinfo acc.conf.acc_monitor.vcc.file)
	[[ ${str_tmp} != "null" ]] && file=${str_tmp}

	str_tmp=$(get_confinfo acc.conf.acc_monitor.vcc.interval)
	[[ ${str_tmp} != "null" ]] && interval2=${str_tmp}


	echo "${delay} ${interval} ${command} ${file} ${file1} ${interval1} ${interval2}"
	sleep ${delay}
	${command} -t "${interval}" -v "${interval2}" -d "${interval1}" -l "${file}" -p "${file1}" 1>/dev/null &
}

main() {
	local func_path_tmp=$(get_confinfo acc.path)
	[[ "${func_path_tmp}" != "null" ]] && func_path=${func_path_tmp}
	
	local acc_config=${func_path}/acc.conf
	local tmp=${func_path}/.config_acc
	local alias command
	
	sed '/#/d;/^$/d' ${acc_config} > ${tmp}

	while read alias command; do
		[[ "${alias}" = "acc_monitor" || "${alias}" = "move_log" || "${alias}" = "onoff_check" ]] \
			&& start_${alias} ${command} &
	done < ${tmp}

	rm ${tmp}
}

main "$@"
