#!/bin/bash

func_path=/tmp/config

#
# $1: command
#
stop_function() {
	local command=$1

	echo "${command}"
	command_kill ${command}
}

stop_main() {
	command_kill acc_init
}

main() {
	local func_path_tmp=$(get_confinfo acc.path)
	[[ "${func_path_tmp}" != "null" ]] && func_path=${func_path_tmp}
	
	local acc_config=${func_path}/acc.conf
	local tmp=${func_path}/.config_acc
	local alias command
	
	sed '/#/d;/^$/d' ${acc_config} > ${tmp}

	while read alias command; do
		[[ "${alias}" = "acc_monitor" || "${alias}" = "move_log" || "${alias}" = "onoff_check" ]] \
			&& stop_function ${command}
	done < ${tmp}
	
	stop_main

	rm ${tmp}
}

main "$@"
