#!/bin/bash

main() {
	local interval=$1

	[[ -z ${interval} ]] && exit
	acc_exit 1> /dev/null
	set_confinfo acc.conf.acc_monitor.timeout "${interval}"
	acc_init 1> /dev/null

	echo "acc.timeout=${interval}s"
}
main "$@"
