#!/bin/bash

main() {
	local key=$1
	local file=$(get_sysinfo_path ${key})
	local value="none"
	
	if [[ -f "${file}" ]];then
		value=$(cat ${file})
		if [[ -z "${value}" ]];then
			#error_action "${target}"
			echo "null"
		fi
	fi
	echo "${value}"
}

main "$@"