#!/bin/bash

func_path=/tmp/config
gps_device="/dev/ttyAMA2"

#
# $1: command
#
stop_function() {
	local command=$1

	echo "${command}"
	command_kill ${command}
}

stop_main() {
	command_kill gps_init
}

main() {
	local func_path_tmp=$(get_confinfo gps.path)
	[[ "${func_path_tmp}" != "null" ]] && func_path=${func_path_tmp}
	
	local gps_config=${func_path}/gps.conf
	local tmp=${func_path}/.config_gps
	local alias command

	sed '/#/d;/^$/d' ${gps_config} > ${tmp}

	while read alias command; do
		[[ "${alias}" = "move_log" || "${alias}" = "obtain_data" || "${alias}" = "anlysis_data" ]] \
			&& stop_function ${command}
	done < ${tmp}
	
	stop_main
	
	rm ${tmp}
}

main "$@"
