#!/bin/bash

gps_path=/tmp/config
gps_config=${gps_path}/gps.conf
gps_config_tmp=${gps_path}/.config_gps
gps_device="/dev/ttyAMA2"
gps_device_tmp=${gps_device}

#
# $1: delay, $2: interval, $3: output file, $4: command, $5: debug path
#
stop_function() {
	local delay=$1
	local interval=$2
	local output=$3
	local command=$4
	local dpath=$5

	echo "${command}"
	command_kill ${command}
}

stop_main() {
	command_kill gps_init
}

main() {
	local tmp=${gps_config_tmp}

	sed '/#/d;/^$/d' ${gps_config} > ${tmp}

	local alias delay interval file command file1
	while read alias delay interval file command file1; do
		[[ "${alias}" = "move_log" || "${alias}" = "obtain_data" || "${alias}" = "anlysis_data" ]] \
			&& stop_function ${delay} ${interval} ${file} ${command} ${file1}
	done < ${tmp}
	stop_main
}

main "$@"
