#!/bin/bash

led_path=/tmp/config
led_config=${led_path}/led.conf
led_config_tmp=${led_path}/.config_led

#
# $1: delay, $2: interval, $3: input path, $4: command, $5: output file
#
stop_function() {
	local delay=$1
	local interval=$2
	local input=$3
	local command=$4
	local output=$5

	echo "${command}"
	command_kill ${command}
}

stop_main() {
	command_kill led_init
}

main() {
	local tmp=${led_config_tmp}

	sed '/#/d;/^$/d' ${led_config} > ${tmp}

	local alias delay interval file command file1
	while read alias delay interval file command file1; do
		[[ "${alias}" = "led_reload" || "${alias}" = "led_main" ]] && stop_function ${delay} ${interval} ${file} ${command} ${file1}
	done < ${tmp}
	stop_main
}

main "$@"
