#!/bin/bash

func_path=/tmp/config

#
# $1: command
#
stop_function() {
	local command=$1

	echo "${command}"
	command_kill ${command}
}

stop_main() {
	command_kill led_init
}

main() {
	local func_path_tmp=$(get_confinfo led.path)
	[[ "${func_path_tmp}" != "null" ]] && func_path=${func_path_tmp}
	
	local led_config=${func_path}/led.conf
	local tmp=${func_path}/.config_led
	local alias command
	
	sed '/#/d;/^$/d' ${led_config} > ${tmp}

	while read alias command; do
		[[ "${alias}" = "led_reload" || "${alias}" = "led_main" ]] \
			&& stop_function ${command}
	done < ${tmp}

	stop_main
	
	rm ${tmp}
}

main "$@"
