#!/bin/bash

echo "--ACC off about $(cat /tmp/.acc/duration)s--"
echo "--Prepare to SHUT DOWN!--"

#close all the leds
acc_closeled() {
	sysled main off
}

#save vcc log
acc_vcclog() {
	move_vcc.sh
}

#cp ap syslog
syslog_copy() {
	local cmd="/etc/jsock/jmsg.sh asyn acc_off {\"date\":\"${time}\"}"
	echo "$0: ${cmd}"
	${cmd} &
}

#save 3g log
acc_3glog() {
	move_3g.sh
}

#write onoff log
acc_onfflog() {
	onofflog "ACC-OFF"
	echo "ACC-OFF" > /data/.off_reason
}

acc_unregister() {
	echo "--Unregister--"
	#/ect/platform/bin/cancellation.sh
}

#device shutdown
acc_shutdown() {
	echo "--SHUT DOWN!--"
	sysreboot
}

main() {
	acc_closeled
	acc_vcclog
	syslog_copy
	acc_onfflog
	acc_3glog
	acc_unregister
	sync
	acc_shutdown
}

main "$@"
