#!/bin/bash

#
# $1: key, $2: value, $3:path
#
main() {
	local key=$1
	local value=$2
	local err=0
	local file=$(get_sysinfo_path "${key}")

	[[ -z ${file} || -z ${value} ]] && exit
	[[ ! -f "${file}" ]] && (
		local path=${file%/*}
		mkdir -p ${path}
	)
	
	echo ${value} > ${file}; err=$?
	#[[ ${err} -eq 0 ]] && echo "SET ${key}: ${file} = ${value}"
}

main "$@"
