#!/bin/bash
#
#start 3g
#
start_3g_dial() {
        /usr/sbin/3g/do_get_3ginfo.sh &
        /usr/sbin/3g/get_hdrcsq.sh &
        /usr/sbin/3g/check_sim_state.sh &
        /usr/sbin/3g/3g_connect.sh &
        /usr/sbin/3g/get_3g_state.sh &
        /usr/sbin/3g/get_3g_flow.sh &
}

main() {
	sleep 3
	local slot=$(cat /tmp/3g/slot 2>/dev/null)

        if [[ ! -z  ${slot} ]];then
                start_3g_dial
        else
                logger -t $0 "NO find the 3g module !"
                return 0
        fi
}
main "$@"
