#!/bin/bash


usage() {
	echo "usage:"
	echo "[sys|sata|pwr|alarm|gps|3g_led1|3g_led2] [on|off|blink]"
	echo "    sys: for sys led"
	echo "    sata: for sata led"
	echo "    pwr: for power led"
	echo "    gps: for gps led"
	echo "    alarm: for alarm led"
	echo "    3g_led1: for 3g1 led"
	echo "    3g_led2: for 3g2 led"
	echo ""
	echo "    on: 	 led on"
	echo "    off: 	 led off"
	echo "    blink: led blink"
	echo
}

#
#$1:on/off
#
main() {
	local led=$1
	local action=$2
	local err=0

	if [ "2" != "$#" ]; then
		usage

		return
	fi

	case "${led}" in
	"main"|"sys"|"sata"|"gps"|"alarm"|"pwr"|"3g_led1"|"3g_led2")
		;;
	*)
		echo "no support ${led} led"

		return ${e_inval}
		;;
	esac

	case "${action}" in
	"on")
		#
		# 0 is on
		#
		# gpio ${led}=0; err=$?
		echo "up" > /tmp/leds/${led}/status; err=$?
		;;
	"off")
		#
		# 1 is off
		#
		# gpio ${led}=1; err=$?
		echo "down" > /tmp/leds/${led}/status; err=$?
		;;
	"blink")
		#
		# default interval=2
		#
		echo "blink" > /tmp/leds/${led}/status; err=$?
		;;
	*)
		echo "no support ${led} led ${action}"

		err=${e_inval}
		;;
	esac

	return ${err}
}

main "$@"
