#!/bin/bash

um_create() {
	local argc=$#
	local mac="$1"
	local ip="$2"

	if ((2!=argc)); then
		return 1
	fi

	echo "create $@"
}

um_bind() {
	local argc=$#
	local mac="$1"
	local ip="$2"

	if ((2!=argc)); then
		return 1
	fi

	echo "bind $@"
}

um_unbind() {
	local argc=$#
	local mac="$1"
	local ip="$2"

	if ((2!=argc)); then
		reutrn 1
	fi

	echo "unbind $@"
}

um_auth() {
	local argc=$#
	local mac="$1"
	local ip="$2"

	if ((2!=argc)); then
		return 1
	fi

	echo "auth $@"
}

um_deauth() {
	local argc=$#
	local mac="$1"
	local ip="$2"
	local reason="$3"

	if ((3!=argc)); then
		return 1
	fi

	echo "deauth $@"
}

um_limit() {
	local argc=$#
	local mac="$1"
	local ip="$2"; shift 2
	local json="$*"

	if ((argc<3)); then
		reutrn 1
	fi

	echo "limit $@"
}

main() {
	local action="$1"; shift

	case ${action} in
	create|bind|unbind|auth|deauth|limit)
		um_${action} "$@"
		;;
	*)
		return 1
		;;
	esac
}

main "$@"
