#!/bin/bash

#common
pro_path="/tmp/.product"
force_pro_path="/etc/force/pro"
pro_cmd="/bin/atenv"
aute_pro_path="/tmp/.autelan/product"

softwareinfo_path="/tmp/.software_info"
force_softwareinfo_path="/etc/force/sf"
softwareinfo_default_path="/etc/.sf_version"
aute_softwareinfo_path="/tmp/.autelan/softwareinfo"

sys_file="/etc/utils/sysinfo_dir.in"

. /etc/utils/jlog.in

get_pro_info_func() {
	
	local target=$1
	local board_info=$2
	
	local file="${force_pro_path}/${target}"
	local oem_info=$(${pro_cmd} infos/oem/${target})
	local pro_info=$(${pro_cmd} infos/product/${target})
	if [ -f "${file}" ];then
		board_info=$(cat ${file})

	else if [[ -z "${oem_info}" ]];then
			
			if [[ -z "${pro_info}" ]];then
				jcrit_kvs "get_productinfo" "warning" "cannot get $1"
			else
				board_info="${pro_info}"
			fi
		else
			board_info="${oem_info}"
		fi
	fi
	
	echo "${board_info}" > ${pro_path}/${target}
	echo "${pro_info}" > ${aute_pro_path}/${target}
	
}


get_info_func() {
	local array_target=$1
	local array_default=$2
	local func=$3
	local count=${#array_target[*]}
	local i
	
	for ((i=0; i<count; i++)); do
		local key="${array_target[$i]}"
		local value="${array_default[$i]}"
		${func} "${key}" "${value}"
	done
}

get_pro_info() {
	local array_target=('lms' 'mac' 'sn' 'vendor' 'company' 'model')
	local array_default=('lms1.autelan.com' '00-1F-64-00-00-01' 'null' 'null' 'null' 'null')
	
	local count=${#array_target[*]}
	local i
	
	for ((i=0; i<count; i++)); do
		local key="${array_target[$i]}"
		local value="${array_default[$i]}"
		get_pro_info_func "${key}" "${value}"
	done
	
}

get_software_version() {
	local file = "/etc/.version"
	if [ -f "${file}" ];then
		local software_version=$(cat ${file})
		if [ -z "$software_version" ];then
			software_version=invalid
			jcrit_kvs "get_productinfo" "warning" "cannot get software version"
		fi
	else
		software_version=invalid
	fi
	echo "$software_version" > ${softwareinfo_path}/sw.version	
}

get_config_version() {
	local file = "/config/download/ver.info"
	if [ -f "${file}" ];then
		local config_version=$(cat ${file})
		if [ -z "$config_version" ];then
			config_version=invalid
		fi
	else
		config_version=invalid
	fi
	echo "$config_version" > ${softwareinfo_path}/cfg.version	
}


get_gateway_version() {
	local gateway_version="`cat ${__CP_WEBSITE__}/ver.info 2>/dev/null`"
	if [ -z "$gateway_version" ];then
		gateway_version=null
	fi
	echo "$gateway_version" > ${softwareinfo_path}/portal.version
}

get_content_version() {
	local content_version="`cat ${__CP_WEBSITE__}/ver.info 2>/dev/null`"
	if [ -z "$content_version" ];then
		content_version=null
	fi
	echo "$content_version" > ${softwareinfo_path}/content.version
}
get_software_info() {
	get_software_version
	get_config_version
	get_gateway_version
	get_content_version
}

main() {
	mkdir -p ${pro_path}
	mkdir -p ${aute_pro_path}
	mkdir -p ${softwareinfo_path}
	mkdir -p ${aute_softwareinfo_path}
	get_pro_info
	get_software_info
}

main "$@"